# RETO

Os animamos a que realicéis este ejercicio inspirado en el proyecto indicado por Aemet. En nuestro caso emplearemos como fuente de datos un repositorio abierto, el de la universidad de Irvine: 
Repositorio: https://archive.ics.uci.edu/ml/datasets/Forest+Fires


Deberemos analizar y transformar los datos buscando un buen predictor para la variable de área afectada. Dado que se trata de una serie con gran cantidad de ceros (por suerte) nos recomiendan emplear una transformación logarítmica de los datos.
Transformación del logaritmo: https://www.cuemath.com/algebra/log-to-exponential-form/

Estudio de AEMET

[AEMET Estadística del índice meteorológico de riesgo de incendio](AEMET.pdf)

## DATA

Cortez,Paulo and Morais,Anbal. (2008). Forest Fires. UCI Machine Learning Repository. https://doi.org/10.24432/C5D88D.

In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\diego\appdata\local\programs\python\python311\lib\site-packages (from ucimlrepo) (2.2.2)
Collecting certifi>=2020.12.5
  Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
     -------------------------------------- 163.0/163.0 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in c:\users\diego\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\diego\appdata\roaming\python\python311\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\diego\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\diego\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\diego\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Installing collected packages: certifi, ucimlrepo
Successfully installed certifi-2024.7.4 ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
forest_fires = fetch_ucirepo(id=162) 
  
# data (as pandas dataframes) 
X = forest_fires.data.features 
y = forest_fires.data.targets 
  
# metadata 
print(forest_fires.metadata) 
  
# variable information 
print(forest_fires.variables)

{'uci_id': 162, 'name': 'Forest Fires', 'repository_url': 'https://archive.ics.uci.edu/dataset/162/forest+fires', 'data_url': 'https://archive.ics.uci.edu/static/public/162/data.csv', 'abstract': 'This is a difficult regression task, where the aim is to predict the burned area of forest fires, in the northeast region of Portugal, by using meteorological and other data (see details at: http://www.dsi.uminho.pt/~pcortez/forestfires).', 'area': 'Climate and Environment', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 517, 'num_features': 12, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['area'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2007, 'last_updated': 'Thu Jan 11 2024', 'dataset_doi': '10.24432/C5D88D', 'creators': ['Paulo Cortez', 'Anbal Morais'], 'intro_paper': {'title': 'A data mining approach to predict forest fires using meteorological data', 'authors': 'P. Cortez, Aníbal de Jesus Raimundo Morais', 'published_in': 'New Trends in Artificial Intelligence, Proceedings of the 13th EPIA 2007 - Portuguese Conference on Artificial Intelligence', 'year': 2007, 'url': 'https://www.semanticscholar.org/paper/A-data-mining-approach-to-predict-forest-fires-data-Cortez-Morais/0f529dc2b2b2bad22394454d4cba79e2c319f0b0', 'doi': None}, 'additional_info': {'summary': "In [Cortez and Morais, 2007], the output 'area' was first transformed with a ln(x+1) function.\r\n   Then, several Data Mining methods were applied. After fitting the models, the outputs were\r\n   post-processed with the inverse of the ln(x+1) transform. Four different input setups were\r\n   used. The experiments were conducted using a 10-fold (cross-validation) x 30 runs. Two\r\n   regression metrics were measured: MAD and RMSE. A Gaussian support vector machine (SVM) fed\r\n   with only 4 direct weather conditions (temp, RH, wind and rain) obtained the best MAD value:\r\n   12.71 +- 0.01 (mean and confidence interval within 95% using a t-student distribution). The\r\n   best RMSE was attained by the naive mean predictor. An analysis to the regression error curve\r\n   (REC) shows that the SVM model predicts more examples within a lower admitted error. In effect,\r\n   the SVM model predicts better small fires, which are the majority. ", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "For more information, read [Cortez and Morais, 2007].\r\n   1. X - x-axis spatial coordinate within the Montesinho park map: 1 to 9\r\n   2. Y - y-axis spatial coordinate within the Montesinho park map: 2 to 9\r\n   3. month - month of the year: 'jan' to 'dec' \r\n   4. day - day of the week: 'mon' to 'sun'\r\n   5. FFMC - FFMC index from the FWI system: 18.7 to 96.20\r\n   6. DMC - DMC index from the FWI system: 1.1 to 291.3 \r\n   7. DC - DC index from the FWI system: 7.9 to 860.6 \r\n   8. ISI - ISI index from the FWI system: 0.0 to 56.10\r\n   9. temp - temperature in Celsius degrees: 2.2 to 33.30\r\n   10. RH - relative humidity in %: 15.0 to 100\r\n   11. wind - wind speed in km/h: 0.40 to 9.40 \r\n   12. rain - outside rain in mm/m2 : 0.0 to 6.4 \r\n   13. area - the burned area of the forest (in ha): 0.00 to 1090.84 \r\n   (this output variable is very skewed towards 0.0, thus it may make\r\n    sense to model with the logarithm transform).", 'citation': None}}
     name     role         type demographic  \
0       X  Feature      Integer        None
1       Y  Feature      Integer        None
2   month  Feature  Categorical        None
3     day  Feature  Categorical        None
4    FFMC  Feature   Continuous        None
5     DMC  Feature      Integer        None
6      DC  Feature   Continuous        None
7     ISI  Feature   Continuous        None
8    temp  Feature   Continuous        None
9      RH  Feature      Integer        None
10   wind  Feature   Continuous        None
11   rain  Feature      Integer        None
12   area   Target      Integer        None

                                          description            units  \
0   x-axis spatial coordinate within the Montesinh...             None
1   y-axis spatial coordinate within the Montesinh...             None
2                  month of the year: 'jan' to 'dec'              None
3                     day of the week: 'mon' to 'sun'             None
4       FFMC index from the FWI system: 18.7 to 96.20             None
5        DMC index from the FWI system: 1.1 to 291.3              None
6          DC index from the FWI system: 7.9 to 860.6             None
7         ISI index from the FWI system: 0.0 to 56.10             None
8                           temperature: 2.2 to 33.30  Celsius degrees
9                      relative humidity: 15.0 to 100                %
10                           wind speed: 0.40 to 9.40             km/h
11                          outside rain: 0.0 to 6.4             mm/m2
12  the burned area of the forest: 0.00 to 1090.84...               ha

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no

In [3]:
forest_fires.data.features.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0

In [8]:
forest_fires.data.features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    object
 3   day     517 non-null    object
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
dtypes: float64(7), int64(3), object(2)
memory usage: 48.6+ KB

In [5]:
forest_fires.data.features.describe()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000

In [6]:
forest_fires.data.targets.head()

   area
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0

In [9]:
forest_fires.data.features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    object
 3   day     517 non-null    object
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
dtypes: float64(7), int64(3), object(2)
memory usage: 48.6+ KB

In [7]:
forest_fires.data.targets.describe()

              area
count   517.000000
mean     12.847292
std      63.655818
min       0.000000
25%       0.000000
50%       0.520000
75%       6.570000
max    1090.840000